insert into user_profile (email, pass, name, last_name, race, dob) value ('gollum@shiremail.com', 'KPga3Tfn', 'Gollum', NULL, 'Hobbits', 'TA 2430');
insert into user_profile (email, pass, name, last_name, race, dob) value ('arago.elessar@shiremail.com', '9%tAbfB^', 'Aragorn II', 'Elessar', 'Men', 'March 1, TA 2931');
insert into user_profile (email, pass, name, last_name, race, dob) value ('sauron@shiremail.com', 'gMFzh%Nk', 'Sauron', NULL, 'Ainur (Maiar)', 'Before the Ainulindalë');
insert into user_profile (email, pass, name, last_name, race, dob) value ('gandalf@shiremail.com', 'i!Xvfd%M', 'Gandalf', NULL, 'Ainur (Maiar)', 'Before the Shaping of Arda');
insert into user_profile (email, pass, name, last_name, race, dob) value ('bilbo.baggins@shiremail.com', '1nDBeM)F', 'Bilbo', 'Baggins', 'Hobbits', '22 September, TA 2890 (SR 1290)');
insert into user_profile (email, pass, name, last_name, race, dob) value ('frodo.baggins@shiremail.com', 'SzwoPPl^', 'Frodo', 'Baggins', NULL, 'September 22, TA 2968 (SR 1368)');
insert into user_profile (email, pass, name, last_name, race, dob) value ('bombur@shiremail.com', 'awbu(lgp', 'Bombur', NULL, 'Dwarves', NULL);
insert into user_profile (email, pass, name, last_name, race, dob) value ('galion@shiremail.com', 'Pzu6TH*c', 'Galion', NULL, 'Elves', NULL);
insert into user_profile (email, pass, name, last_name, race, dob) value ('bard@shiremail.com', 'AcZ@gpBs', 'Bard', NULL, 'Men', NULL);
insert into user_profile (email, pass, name, last_name, race, dob) value ('roäc@shiremail.com', 'd8^)FNIX', 'Roäc', NULL, 'Raven', 'TA 2788');
