insert into user_profile (email, pass, name, last_name, race, dob) value ('gollum@shiremail.com', 'JTPFFwHl', 'Gollum', NULL, 'Hobbits', 'TA 2430');
insert into user_profile (email, pass, name, last_name, race, dob) value ('arago.elessar@shiremail.com', 'KJgyq@Hu', 'Aragorn II', 'Elessar', 'Men', 'March 1, TA 2931');
insert into user_profile (email, pass, name, last_name, race, dob) value ('sauron@shiremail.com', 'rWG0wCX%', 'Sauron', NULL, 'Ainur (Maiar)', 'Before the Ainulindalë');
insert into user_profile (email, pass, name, last_name, race, dob) value ('gandalf@shiremail.com', '#hGD#%Wu', 'Gandalf', NULL, 'Ainur (Maiar)', 'Before the Shaping of Arda');
insert into user_profile (email, pass, name, last_name, race, dob) value ('bilbo.baggins@shiremail.com', 'pY@u8Bk#', 'Bilbo', 'Baggins', 'Hobbits', '22 September, TA 2890 (SR 1290)');
insert into user_profile (email, pass, name, last_name, race, dob) value ('frodo.baggins@shiremail.com', 'zXsmRVKR', 'Frodo', 'Baggins', NULL, 'September 22, TA 2968 (SR 1368)');
insert into user_profile (email, pass, name, last_name, race, dob) value ('bombur@shiremail.com', '&^RPBAEi', 'Bombur', NULL, 'Dwarves', NULL);
insert into user_profile (email, pass, name, last_name, race, dob) value ('galion@shiremail.com', 'WuolD15d', 'Galion', NULL, 'Elves', NULL);
insert into user_profile (email, pass, name, last_name, race, dob) value ('samwi.gamgee@shiremail.com', 'DDHfETVd', 'Samwise', 'Gamgee', 'Hobbits', 'April 6, TA 2980/SR 1380');
insert into user_profile (email, pass, name, last_name, race, dob) value ('glóin@shiremail.com', '!kL&hpoF', 'Glóin', NULL, 'Dwarves', 'TA 2783');
