insert into user_profile (email, name, last_name, race, dob) value ('Gollum@shiremail.com', 'Gollum', NULL, 'Hobbits', 'TA 2430');
insert into user_profile (email, name, last_name, race, dob) value ('Arago.Elessar@shiremail.com', 'Aragorn II', 'Elessar', 'Men', 'March 1, TA 2931');
insert into user_profile (email, name, last_name, race, dob) value ('Sauron@shiremail.com', 'Sauron', NULL, 'Ainur (Maiar)', 'Before the Ainulindalë');
insert into user_profile (email, name, last_name, race, dob) value ('Gandalf@shiremail.com', 'Gandalf', NULL, 'Ainur (Maiar)', 'Before the Shaping of Arda');
insert into user_profile (email, name, last_name, race, dob) value ('Bilbo.Baggins@shiremail.com', 'Bilbo', 'Baggins', 'Hobbits', '22 September, TA 2890 (SR 1290)');
insert into user_profile (email, name, last_name, race, dob) value ('Frodo.Baggins@shiremail.com', 'Frodo', 'Baggins', NULL, 'September 22, TA 2968 (SR 1368)');
insert into user_profile (email, name, last_name, race, dob) value ('Bombur@shiremail.com', 'Bombur', NULL, 'Dwarves', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Galion@shiremail.com', 'Galion', NULL, 'Elves', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Bard@shiremail.com', 'Bard', NULL, 'Men', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Roäc@shiremail.com', 'Roäc', NULL, 'Raven', 'TA 2788');
insert into user_profile (email, name, last_name, race, dob) value ('Bolg@shiremail.com', 'Bolg', NULL, 'Goblin/Orc', 'Unknown');
insert into user_profile (email, name, last_name, race, dob) value ('Beorning@shiremail.com', 'Beorning', NULL, NULL, NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Balin@shiremail.com', 'Balin', NULL, 'Dwarves', 'TA 2763');
insert into user_profile (email, name, last_name, race, dob) value ('Samwi.Gamgee@shiremail.com', 'Samwise', 'Gamgee', 'Hobbits', 'April 6, TA 2980/SR 1380');
insert into user_profile (email, name, last_name, race, dob) value ('Sting@shiremail.com', 'Sting', NULL, NULL, NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Bella.Baggins@shiremail.com', 'Belladonna (Took)', 'Baggins', 'Hobbits', 'TA 2852 (SR 1252)');
insert into user_profile (email, name, last_name, race, dob) value ('Smaug@shiremail.com', 'Smaug', NULL, 'Dragons', 'Unknown');
insert into user_profile (email, name, last_name, race, dob) value ('Óin@shiremail.com', 'Óin', NULL, 'Dwarves', 'TA 2774[1]');
insert into user_profile (email, name, last_name, race, dob) value ('Glóin@shiremail.com', 'Glóin', NULL, 'Dwarves', 'TA 2783');
insert into user_profile (email, name, last_name, race, dob) value ('Balin@shiremail.com', 'Balin', NULL, 'Dwarves', 'TA 2763');
insert into user_profile (email, name, last_name, race, dob) value ('Glamdring@shiremail.com', 'Glamdring', NULL, NULL, NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Orcrist@shiremail.com', 'Orcrist', NULL, NULL, NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Elrond@shiremail.com', 'Elrond', NULL, 'Half-elven (chose to be immortal)', 'FA 532[1]');
insert into user_profile (email, name, last_name, race, dob) value ('Dori@shiremail.com', 'Dori', NULL, 'Dwarves', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Beorn@shiremail.com', 'Beorn', NULL, 'Man (Skin-changer)', 'Unknown');
insert into user_profile (email, name, last_name, race, dob) value ('Galadriel@shiremail.com', 'Galadriel', NULL, 'Elves', 'YT 1362');
insert into user_profile (email, name, last_name, race, dob) value ('Celeborn@shiremail.com', 'Celeborn', NULL, 'Elves', 'Uncertain; possibly Years of the Trees');
insert into user_profile (email, name, last_name, race, dob) value ('Witch.Angmar@shiremail.com', 'Witch-king of', 'Angmar', 'Man (Wraith)', 'Second Age');
insert into user_profile (email, name, last_name, race, dob) value ('Shelob@shiremail.com', 'Shelob', NULL, 'Spiders', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Phial.Galadriel@shiremail.com', 'Phial of', 'Galadriel', NULL, NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Gwaihir@shiremail.com', 'Gwaihir', NULL, 'Great Eagles', 'Unknown');
insert into user_profile (email, name, last_name, race, dob) value ('Landroval@shiremail.com', 'Landroval', NULL, 'Eagle', 'Possibly First Age');
insert into user_profile (email, name, last_name, race, dob) value ('Meneldor@shiremail.com', 'Meneldor', NULL, 'Eagles', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Will.Whitfoot@shiremail.com', 'Will', 'Whitfoot', 'Hobbit', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Rosie.Cotton@shiremail.com', 'Rosie', 'Cotton', 'Hobbits', 'TA 2984 (SR 1384)[1]');
insert into user_profile (email, name, last_name, race, dob) value ('Boromir@shiremail.com', 'Boromir', NULL, 'Men', 'TA 2978');
insert into user_profile (email, name, last_name, race, dob) value ('Legolas@shiremail.com', 'Legolas', NULL, 'Elves', NULL);
insert into user_profile (email, name, last_name, race, dob) value ('Gimli@shiremail.com', 'Gimli', NULL, 'Dwarves', 'TA 2879');
insert into user_profile (email, name, last_name, race, dob) value ('Thori.Oakenshield@shiremail.com', 'Thorin II', 'Oakenshield', 'Dwarves', 'TA 2746');
insert into user_profile (email, name, last_name, race, dob) value ('Durin.Bane@shiremail.com', 'Durin's', 'Bane', NULL, 'Before the creation of Arda');
insert into user_profile (email, name, last_name, race, dob) value ('Primu.Baggins@shiremail.com', 'Primula (Brandybuck)', 'Baggins', 'Hobbits', 'TA 2920 (SR 1320)');
insert into user_profile (email, name, last_name, race, dob) value ('Pereg.Took@shiremail.com', 'Peregrin', 'Took', 'Hobbits', 'Spring TA 2990/SR 1390[1]');
insert into user_profile (email, name, last_name, race, dob) value ('Meria.Brandybuck@shiremail.com', 'Meriadoc', 'Brandybuck', 'Hobbit', 'TA 2982/SR 1382');
